# Generated by Django 2.0.4 on 2018-04-03 07:46

import apps.iot.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.iot.models.alarm_song_upload_path)),
                ('time', models.TimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('allow_snooze', models.BooleanField(default=True)),
                ('repeat_mon', models.BooleanField(default=True)),
                ('repeat_tue', models.BooleanField(default=True)),
                ('repeat_wed', models.BooleanField(default=True)),
                ('repeat_thu', models.BooleanField(default=True)),
                ('repeat_fri', models.BooleanField(default=True)),
                ('repeat_sat', models.BooleanField(default=True)),
                ('repeat_sun', models.BooleanField(default=True)),
            ],
        ),
    ]
