# Generated by Django 2.0.4 on 2018-04-04 06:10

import apps.iot.models
import cms.utils.md5_file_field
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='upload',
        ),
        migrations.AddField(
            model_name='alarm',
            name='last_synchronized',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='sound',
            field=cms.utils.md5_file_field.MD5FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.iot.models.alarm_song_upload_path),
        ),
        migrations.AddField(
            model_name='alarm',
            name='sound_md5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
