# Generated by Django 2.0.4 on 2018-04-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20180403_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
