# Generated by Django 2.0.4 on 2018-05-10 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20180505_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmClientAlarmSynchronized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synchronized', models.DateTimeField(blank=True, null=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Alarm')),
            ],
        ),
        migrations.RemoveField(
            model_name='alarmclient',
            name='last_synchronized',
        ),
        migrations.AddField(
            model_name='alarmclientalarmsynchronized',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.AlarmClient'),
        ),
    ]
